name: ut_media
description: Ubuntu Touch PulseAudio voice recording, Xylo alert, and haptic.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      elinux:
        pluginClass: UtMediaPlugin
